name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_json_to_csv:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./json_to_csv_processor
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest

  build_and_push_jumbo_scraper:
    needs: test_json_to_csv
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jumbo_scraper
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./jumbo_scraper
        push: true
        tags: osvalois/jumbo-scraper:latest,osvalois/jumbo-scraper:${{ github.sha }}

  deploy_jumbo_scraper:
    needs: build_and_push_jumbo_scraper
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jumbo_scraper
    steps:
    - uses: actions/checkout@v2
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy to fly.io
      run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  process_json_to_csv:
    needs: test_json_to_csv
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./json_to_csv_processor
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run JSON to CSV processor
      run: python main.py
    - name: Upload CSV artifact
      uses: actions/upload-artifact@v2
      with:
        name: output-product
        path: ./json_to_csv_processor/output-product.csv